const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const fixture=require('./teacher-dashboard.fixture.cjs');
const read=name=>fs.readFileSync(path.resolve(__dirname,'../../frontend',name),'utf8');
const wait=()=>new Promise(r=>setTimeout(r,30));

(async()=>{
  const {Window}=await import(pathToFileURL(require.resolve('happy-dom')).href);
  const windows=[];
  const make=async(initial=fixture(),failed=false,file='teacher.html')=>{
    const w=new Window({url:'http://localhost/'+file+(file==='grades.html'?'?assignment=hw3':''),settings:{enableJavaScriptEvaluation:true,
      disableJavaScriptFileLoading:true,disableCSSFileLoading:true,suppressInsecureJavaScriptEnvironmentWarning:true}});
    windows.push(w);
    w.document.write(read(file).replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,''));
    let fail=failed, payload=initial;
    const requests=[],paths=[];
    w.fetch=async(url,options)=>{
      const p=new URL(url,'http://localhost');
      paths.push(p.pathname);
      let data={};
      if(p.pathname==='/auth/me')data={student_id:'teacher-fixture',name:'Pat Teacher',role:'teacher'};
      if(p.pathname==='/assignments')data={assignments:initial.assignments};
      if(p.pathname==='/assignment_template')data={content:'def sample():\n    pass'};
      if(p.pathname==='/teacher/dashboard'){
        requests.push({url:p,options});
        data=p.searchParams.has('assignment_id')?fixture(p.searchParams.get('assignment_id')):payload;
        if(fail)return new w.Response('{}',{status:503});
      }
      return new w.Response(JSON.stringify(data),{status:200,headers:{'Content-Type':'application/json'}});
    };
    const script=file==='grades.html'?'grades.js':file==='teacher-assignments.html'?'teacher.js':'teacher-insights.js';
    w.eval(read('ui.js')+'\n'+read('cache.js')+'\n'+read(script));
    await wait();
    return {w,doc:w.document,requests,paths,setFail:v=>fail=v,setData:v=>payload=v};
  };
  try{
    const {w,doc,requests,paths,setFail,setData}=await make();
    assert.equal(doc.querySelector('#list'),null);
    assert.equal(doc.querySelector('#newAssignment'),null);
    assert.equal(doc.querySelector('#uploadDrawer'),null);
    assert.equal(paths.includes('/assignments'),false);
    assert.equal(paths.includes('/assignment_template'),false);
    assert.equal(doc.querySelector('[data-nav="Home"]').getAttribute('aria-current'),'page');
    assert.equal(doc.querySelector('[data-nav="Assignments"]').getAttribute('href'),'teacher-assignments.html');
    assert.equal(doc.querySelectorAll('[data-insight-problem]').length,6);
    assert.equal(doc.querySelector('#insightFocus').hidden,true,'Detailed records start out of view');
    assert.match(doc.querySelector('#chartExplanation').textContent,/incorrect answer and hasn’t corrected it yet/);
    assert.match(doc.querySelector('.insight-bar-count').textContent,/8 students may need help/);
    assert.match(doc.querySelector('.insight-bar-count').textContent,/16 students tried this problem/);
    assert.equal(doc.querySelectorAll('.insight-track i').length,6,'Each bar shows only one measure');
    assert.equal(requests[0].options.cache,'no-store');
    doc.querySelector('[data-insight-problem]').click();
    assert.equal(doc.querySelector('#insightDetailTitle').textContent,'Invert a dictionary');
    assert.equal(doc.querySelectorAll('.insight-students li').length,8);
    assert.equal(doc.querySelector('.insight-students details').open,false);
    doc.querySelector('.insight-students summary').click();
    assert.equal(doc.querySelector('.insight-students details').open,true);
    assert.equal(new URL(doc.querySelector('.insight-detail-grid a').href).searchParams.get('assignment'),'lab1');
    const second=doc.querySelectorAll('[data-insight-problem]')[1];
    second.focus();second.click();
    assert.equal(doc.activeElement.id,'insightDetailTitle','Opening details moves focus to the selected problem');
    assert.equal(second.getAttribute('aria-expanded'),'true');
    assert.equal(doc.querySelector('#insightDetailTitle').textContent,'Evaluate postfix expressions');
    doc.querySelector('#closeInsightDetail').click();
    assert.equal(doc.querySelector('#insightFocus').hidden,true);
    assert.equal(doc.activeElement,second,'Closing details returns focus to the problem');
    assert.equal(second.getAttribute('aria-expanded'),'false');
    doc.querySelector('#showAllInsights').click();
    assert.equal(doc.querySelectorAll('[data-insight-problem]').length,8);
    doc.querySelectorAll('[data-insight-problem]')[7].click();
    doc.querySelector('#showAllInsights').click();
    doc.querySelector('#closeInsightDetail').click();
    assert.equal(doc.activeElement.id,'showAllInsights','A hidden chart row returns focus to Show all');
    doc.querySelector('#reviewPriority').click();
    assert.equal(doc.activeElement.id,'insightDetailTitle');
    doc.querySelector('#insightAssignment').value='hw3';
    doc.querySelector('#insightAssignment').dispatchEvent(new w.Event('change'));await wait();
    assert.equal(doc.querySelectorAll('[data-insight-problem]').length,6);
    assert.equal(requests.at(-1).url.searchParams.get('assignment_id'),'hw3');
    assert.equal(doc.querySelector('#insightFocus').hidden,true,'Changing assignment closes old problem details');
    doc.querySelector('#reviewPriority').click();
    assert.equal(doc.querySelector('#insightDetailTitle').textContent,'Evaluate postfix expressions');
    setFail(true);doc.querySelector('#refreshInsights').click();await wait();
    assert.match(doc.querySelector('#insightNotice').textContent,/last successful update/);
    assert.equal(doc.querySelectorAll('[data-insight-problem]').length,6);
    setFail(false);doc.querySelector('#retryInsights').click();await wait();
    assert.equal(doc.querySelector('#insightNotice').textContent,'');
    // WHAT A TEACHER CAN ACT ON: the step named by what it asked, and the code
    // the student submitted for it, not just "Check step 2".
    doc.querySelector('[data-insight-problem]').click();
    const firstStudent=doc.querySelector('.insight-students details');
    firstStudent.open=true;
    assert.match(firstStudent.textContent,/Step 2: Return the value on top/);
    assert.equal(firstStudent.querySelector('pre.student-code').textContent,
      'if self.top is None:\n    return None\nreturn self.top','their code, verbatim');
    assert.match(doc.querySelector('.insight-steps').textContent,/Step 2: Return the value on top/);
    assert.match(doc.querySelector('.insight-steps').textContent,/Worded differently for some students/);
    // An older snapshot with no details still shows the one-line feedback.
    const legacy=fixture();legacy.problems.forEach(p=>p.follow_up.forEach(s=>delete s.details));
    setData(legacy);doc.querySelector('#insightAssignment').value='';
    doc.querySelector('#insightAssignment').dispatchEvent(new w.Event('change'));await wait();
    doc.querySelector('[data-insight-problem]').click();
    assert.match(doc.querySelector('.student-feedback').textContent,/Feedback to discuss/);
    const unsafe=fixture();unsafe.problems[0].title='<img src=x onerror=alert(1)>';
    unsafe.problems[0].follow_up[0].reason='<script>alert(1)</script>';
    // Student code is the most attacker-shaped text on this page.
    unsafe.problems[0].follow_up[0].details[0].code='<img src=x onerror=alert(2)><script>alert(3)</script>';
    unsafe.problems[0].follow_up[0].details[0].prompt='<img src=x onerror=alert(4)>';
    unsafe.problems[0].steps[0].prompt='<script>alert(5)</script>';
    setData(unsafe);doc.querySelector('#insightAssignment').value='';
    doc.querySelector('#insightAssignment').dispatchEvent(new w.Event('change'));await wait();
    assert.equal(doc.querySelector('#insightAssignment').value,'');
    doc.querySelector('[data-insight-problem]').click();
    doc.querySelectorAll('.insight-students details').forEach(x=>x.open=true);
    assert.equal(doc.querySelectorAll('#classInsights img, #classInsights script').length,0);
    assert.match(doc.querySelector('pre.student-code').textContent,/<img src=x/,'shown as text, not run');
    assert.match(doc.querySelector('#insightDetailTitle').textContent,/<img/);
    const empty=fixture();empty.problems=[];empty.assignments=[];
    empty.summary={students:0,active:0,needs_help:0,problems:0,attempted_problems:0,indeterminate:0};
    const blank=await make(empty);
    assert.match(blank.doc.querySelector('#classInsights').textContent,/Publish an assignment/);
    assert.equal(blank.doc.querySelector('#insightAssignment').disabled,true);
    const bad=await make(fixture(),true);
    assert.equal(bad.doc.querySelectorAll('.insight-board').length,0);
    assert.match(bad.doc.querySelector('#insightNotice').textContent,/temporarily unavailable/);
    bad.setFail(false);bad.doc.querySelector('#retryInsights').click();await wait();
    assert.equal(bad.doc.querySelectorAll('.insight-board').length,1);
    const clear=fixture();clear.summary.needs_help=0;
    clear.problems.forEach(p=>{p.needs_help=0;p.follow_up=[];p.steps.forEach(s=>s.needs_help=0);});
    const caughtUp=await make(clear);
    assert.match(caughtUp.doc.querySelector('#teachingSuggestion').textContent,/No uncorrected answers/);
    assert.equal(caughtUp.doc.querySelector('#reviewPriority'),null);
    assert([...caughtUp.doc.querySelectorAll('.insight-track i')].every(bar=>bar.style.width==='0%'));
    const grades=await make(fixture(),false,'grades.html');
    assert.equal(grades.doc.querySelector('#pick').value,'hw3','Gradebook opens the assignment from the dashboard link');
    const assignments=await make(fixture(),false,'teacher-assignments.html');
    assert.equal(assignments.doc.querySelectorAll('#listBody tbody tr').length,2);
    assert.equal(assignments.doc.querySelector('#classInsights'),null);
    assert.equal(assignments.paths.includes('/teacher/dashboard'),false);
    assert.equal(assignments.doc.querySelector('[data-nav="Assignments"]').getAttribute('aria-current'),'page');
    assert.equal(assignments.doc.querySelector('[data-nav="Home"]').getAttribute('aria-current'),null);
    assignments.doc.querySelector('#newAssignment').click();
    assert.equal(assignments.doc.querySelector('#uploadDrawer').open,true);
    assignments.doc.querySelector('#closeUpload').click();
    assert.equal(assignments.doc.querySelector('#uploadDrawer').open,false);
    console.log('PASS: teacher chart, drill-down, filters, errors, separate assignment navigation, library and upload drawer.');
  }finally{for(const w of windows)await w.happyDOM.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
