/* Staged learning flow with the real UI scripts and synthetic API responses.
   No live database, model, oracle or code execution. Happy DOM cannot test layout. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {pathToFileURL} = require('node:url');
const root = path.resolve(__dirname, '../../frontend');
const read = name => fs.readFileSync(path.join(root, name), 'utf8');
const tick = () => new Promise(resolve => setTimeout(resolve, 30));
const problem = {slug:'employee',title:'Employee Update',description:'Carry employees forward. Keep `records` unchanged.\n\n>>> update(records)\n{"year": 2027}'};
const steps = [{prompt:'Read the previous records.',indent:0},{prompt:'Return the updated records.',indent:0}];
const graph = {nodes:[{id:'n0',kind:'start',label:'Read records'},{id:'n1',kind:'return',label:'Return updates'}],edges:[{src:'n0',dst:'n1'}]};

(async () => {
  const {Window} = await import(pathToFileURL(require.resolve('happy-dom')).href);
  const window = new Window({url:'http://localhost/student.html',width:1600,height:1000,settings:{enableJavaScriptEvaluation:true,disableJavaScriptFileLoading:true,disableCSSFileLoading:true,suppressInsecureJavaScriptEnvironmentWarning:true}});
  const doc = window.document;
  let value = '', selections = [], editorCreations = 0, focusCalls = 0;
  const options = {}, calls = [];
  let approved = false, stepFailure = false, comparisonFailure = false, openingFailure = false, verdict = 'incorrect', history = {found:false}, session = 0;
  try {
    doc.write(read('student.html').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,''));
    window.scrollTo = () => {};
    window.CodeMirror = {fromTextArea:() => {
      editorCreations++;
      return {setOption:(k,v)=>options[k]=v,setSize:()=>{},on:()=>{},refresh:()=>{},focus:()=>focusCalls++,setCursor:()=>{},getGutterElement:()=>({offsetWidth:32}),getValue:()=>value,setValue:v=>value=v,listSelections:()=>selections,setSelections:v=>selections=v};
    }};
    window.fetch = async (url, init={}) => {
      const route = new URL(url,'http://localhost').pathname;
      calls.push({route,body:init.body});
      let data = {}, status = 200;
      if(route==='/auth/me') data={name:'Alex',role:'student',student_id:'synthetic'};
      else if(route==='/assignments') data={assignments:[]};
      else if(route==='/solved') data={slugs:[]};
      else if(route==='/decompose_chunks'){status=openingFailure?503:200;data={session_id:'s'+(++session),header:'def employee_update(records):',chunks:steps.map(s=>({...s,prompt:''}))};}
      else if(route.startsWith('/history/')) data=history;
      else if(route.startsWith('/session_steps/')){status=stepFailure?503:200;data={chunks:steps};}
      else if(route==='/tutor_chat') data={reply:'What changes from one year to the next?',ready:true,offtrack:true};
      else if(route==='/plan_graph') data=graph;
      else if(route==='/design_review/plan'||route==='/design_review') data={approved,reply:approved?'Your approach is approved.':'Explain how you will preserve the earlier records.',plan_graph:graph};
      else if(route==='/grade_chunk'){
        const index=JSON.parse(init.body).expected_index;
        data=verdict==='correct'?{verdict:'correct',reason:'This step passes.',index:index+1,completed:index===1,solved_independently:true}:verdict==='indeterminate'?{verdict:'indeterminate',reason:'The grader is temporarily unavailable.'}:{verdict:'incorrect',reason:'Try the empty-input case.',failing_case:'employee_update({})',attempts:1};
      }
      else if(route==='/mark_solved') data={ok:true};
      else if(route==='/graphs'){status=comparisonFailure?503:200;data={plan:graph,code:graph,comparison:{similarity:1,notes:['The structure matches.']}};}
      else if(route.endsWith('/restart')) data={ok:true};
      else throw new Error('Unexpected request: '+route);
      return new window.Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});
    };
    window.eval(['ui.js','graphs.js','workspace.js','student.js'].map(read).join('\n')+'\nwindow.inspect = code => eval(code);');
    await tick();
    await window.start(problem);
    const visibleStage = () => [...doc.querySelectorAll('.journey-panel')].filter(el=>!el.hidden).map(el=>el.id);
    assert.deepEqual(visibleStage(),['stageRead']);
    assert(doc.querySelector('#statement pre').textContent.includes('update(records)'));
    assert.equal(doc.querySelector('#readSignature').textContent,'def employee_update(records):');
    assert.equal(doc.querySelector('#chatcol').parentElement.id,'chatParking');
    assert.equal(doc.querySelector('#tabCode').getAttribute('aria-disabled'),'true');
    doc.querySelector('#tabCode').click();
    assert.deepEqual(visibleStage(),['stageRead']);
    assert(doc.querySelector('#workspaceNotice').textContent.includes('submit your plan'));
    assert.equal(options.readOnly,'nocursor');
    doc.querySelector('#tabRead').focus();
    doc.querySelector('#tabRead').dispatchEvent(new window.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));
    assert.equal(doc.activeElement.id,'tabPlan');
    doc.querySelector('#readContinue').click();
    assert.deepEqual(visibleStage(),['stagePlan']);
    assert.equal(doc.querySelector('#chatcol').parentElement.id,'planChatHome');
    assert.equal(doc.querySelector('#planSubmitBtn').disabled,true);
    assert.equal(doc.querySelector('#planPreview').open,false);
    doc.querySelector('#cinput').value='My unsent thinking';
    window.choosePlanMethod('upload');
    window.pickDesign(new window.File(['diagram'],'plan.pdf',{type:'application/pdf'}));
    window.choosePlanMethod('chat');
    assert.equal(doc.querySelector('#cinput').value,'My unsent thinking');
    window.choosePlanMethod('upload');
    assert.equal(doc.querySelector('#designName').textContent,'plan.pdf');
    window.choosePlanMethod('chat');
    await window.sendToTutor('I will copy the records and update the salaries.');
    await window.inspect('planQueue');
    assert(doc.querySelector('#fork'),'The tutor’s alternative-approach choices remain available');
    assert.equal(doc.querySelector('#planSubmitBtn').disabled,false);
    await window.submitPlanGraph();
    assert.equal(doc.querySelector('#tabCode').getAttribute('aria-disabled'),'true');
    assert(doc.querySelector('#designMsg').textContent.includes('preserve'));
    approved=true;
    await window.submitPlanGraph(); await tick();
    assert.deepEqual(visibleStage(),['stagePlan'],'Approval must not force a stage change');
    assert.equal(doc.querySelector('#planApproved').hidden,false);
    assert.equal(doc.querySelector('#tabCode').getAttribute('aria-disabled'),'false');
    doc.querySelector('#planContinue').click();
    assert.deepEqual(visibleStage(),['stageCode']);
    assert.equal(doc.querySelector('#stepCount').textContent,'Step 1 of 2');
    value='    draft = records.copy()'; selections=[{anchor:{line:0,ch:7},head:{line:0,ch:12}}];
    const conversation=doc.querySelector('#clog');
    const trigger=doc.querySelector('.code-resources [data-resource="problem"]');
    trigger.focus();trigger.click();
    assert.equal(doc.querySelector('#resourceDrawer').hidden,false);
    assert.equal(doc.querySelector('#page').inert,true);
    assert.equal(doc.querySelector('#problemPaper').parentElement.id,'resourceBody');
    window.openResource('plan');
    assert.equal(doc.querySelector('#problemPaper').parentElement.id,'problemHome');
    window.openResource('tutor');
    assert.equal(doc.querySelector('#clog'),conversation,'One shared conversation across all stages');
    assert.equal(doc.querySelector('#cform').inert,false);
    doc.querySelector('#closeResource').dispatchEvent(new window.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));
    assert.equal(doc.querySelector('#resourceDrawer').hidden,true);
    assert.equal(doc.querySelector('#page').inert,false);
    assert.equal(doc.activeElement,trigger);
    window.chooseWorkspaceStage('read'); window.chooseWorkspaceStage('plan'); window.chooseWorkspaceStage('code');
    assert.equal(value,'    draft = records.copy()');
    assert.equal(editorCreations,1);
    assert.equal(selections[0].head.ch,12);
    doc.querySelector('#focusWork').click();
    assert(doc.body.classList.contains('focus-workspace'));
    window.dispatchEvent(new window.KeyboardEvent('keydown',{key:'Escape'}));
    assert(!doc.body.classList.contains('focus-workspace'));
    await doc.querySelector('#submit').onclick();
    assert(doc.querySelector('#msg .failCase'),'Failure details remain available');
    assert.equal(value,'    draft = records.copy()');
    verdict='indeterminate';await doc.querySelector('#submit').onclick();
    assert.equal(value,'    draft = records.copy()');
    verdict='correct';await doc.querySelector('#submit').onclick();
    assert.equal(doc.querySelector('#reviewBox').hidden,false);
    assert(doc.querySelector('#backToNow').textContent.includes('Continue to step 2'));
    assert(doc.querySelector('#reviewCode').textContent.includes('records.copy()'));
    doc.querySelector('#backToNow').click();
    assert.equal(value,'    ','Continuing must start a new draft, not repeat the submitted answer');
    value='    return updated';comparisonFailure=true;
    await doc.querySelector('#submit').onclick();
    assert.deepEqual(visibleStage(),['stageCode'],'Completion waits for the student to open Reflect');
    assert.equal(doc.querySelector('#finishReview').hidden,false);
    doc.querySelector('#finishReview').click();
    assert.deepEqual(visibleStage(),['stageReflect']);
    assert(doc.querySelector('#reflectSummary').textContent.includes('2 of 2'));
    assert(doc.querySelector('#reflectionCode').textContent.includes('return updated'));
    assert(doc.querySelector('#comparisonStatus button'));
    comparisonFailure=false;doc.querySelector('#comparisonStatus button').click();await tick();
    assert.equal(doc.querySelector('#dualCard').hidden,false);
    assert.equal(doc.querySelector('#comparisonStatus').textContent,'');

    // Upload approval, unavailable step instructions, retry and a safe restart.
    approved=true;await window.start(problem);
    window.chooseWorkspaceStage('plan');window.choosePlanMethod('upload');
    window.pickDesign(new window.File(['diagram'],'plan.pdf',{type:'application/pdf'}));
    stepFailure=true;await window.uploadDesign();await tick();
    assert.equal(doc.querySelector('#planApproved').hidden,false);
    window.chooseWorkspaceStage('code');
    assert.equal(doc.querySelector('#submit').disabled,true);
    assert.equal(options.readOnly,'nocursor');
    assert(doc.querySelector('#msg').textContent.includes('could not be loaded'));
    stepFailure=false;doc.querySelector('#msg button').click();await tick();
    assert.equal(doc.querySelector('#submit').disabled,false);
    window.openRestart();window.closeRestart();
    assert.equal(doc.querySelector('#tabCode').getAttribute('aria-disabled'),'false','Cancel restart keeps approval');
    await window.doRestart();
    assert.deepEqual(visibleStage(),['stageRead']);
    assert.equal(doc.querySelector('#tabCode').getAttribute('aria-disabled'),'true');
    assert.equal(doc.querySelector('#tabReflect').getAttribute('aria-disabled'),'true');
    assert.equal(doc.querySelector('#designPick').hidden,true);
    openingFailure=true;await window.start(problem);
    assert(doc.querySelector('#workspaceStatus button'),'Failed initialization has a visible retry');
    assert.equal(doc.querySelector('#readContinue').disabled,true);
    openingFailure=false;doc.querySelector('#workspaceStatus button').click();await tick();
    assert.equal(doc.querySelector('#readContinue').disabled,false);
    history={found:true,design_approved:true,plan:graph,code:graph,comparison:{similarity:1},messages:[{role:'user',content:'Earlier work'}]};
    await window.start(problem);await tick();
    assert.deepEqual(visibleStage(),['stageRead']);
    assert.equal(doc.querySelector('#tabReflect').getAttribute('aria-disabled'),'false');
    assert(doc.querySelector('#reflectSummary').textContent.includes('previous attempt'));
    assert.equal(doc.querySelector('#reflectionCodeDetails').hidden,true,'Historical graphs cannot claim a new completed function');
    assert.equal(doc.querySelectorAll('#clog').length,1);
    const ids=[...doc.querySelectorAll('[id]')].map(el=>el.id);
    assert.equal(new Set(ids).size,ids.length,'No duplicate IDs');
    assert(calls.some(c=>c.route==='/design_review')&&calls.some(c=>c.route==='/design_review/plan'));
    console.log('PASS: Read → Plan → Code → Reflect; both planning methods; approval gates; draft/chat/file preservation; reference drawer and keyboard focus; paced step progression; grading errors; completion/comparison retry; restart; loading failures; restored work.');
    console.log('DOM behavior only. Browser layout and real CodeMirror still require Chromium.');
  } finally {await window.happyDOM.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
