/* Shared learning workspace with the real UI scripts and synthetic responses.
   No live database, model, oracle or code execution. Happy DOM cannot test layout. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {pathToFileURL} = require('node:url');
const root = path.resolve(__dirname, '../../frontend');
const read = name => fs.readFileSync(path.join(root, name), 'utf8');
const tick = () => new Promise(resolve => setTimeout(resolve, 30));
const problem = {slug:'employee',title:'Employee Update',description:'Carry employees forward. Keep `records` unchanged.\n\n>>> update(records)\n{"year": 2027}'};
const steps = [{prompt:'Read the previous records.',indent:0},{prompt:'Return the updated records.',indent:0}];
const graph = {nodes:[{id:'n0',kind:'start',label:'Read records'},{id:'n1',kind:'return',label:'Return updates'}],edges:[{src:'n0',dst:'n1'}]};

(async () => {
  const {Window} = await import(pathToFileURL(require.resolve('happy-dom')).href);
  const window = new Window({url:'http://localhost/student.html',width:1600,height:1000,settings:{enableJavaScriptEvaluation:true,disableJavaScriptFileLoading:true,disableCSSFileLoading:true,suppressInsecureJavaScriptEnvironmentWarning:true}});
  const doc = window.document;
  let value = '', selections = [], editorCreations = 0, focusCalls = 0;
  const options = {}, calls = [];
  let historyGate=null, historyFailure=false;
  let approved = false, stepFailure = false, comparisonFailure = false, openingFailure = false, verdict = 'incorrect', history = {found:false}, session = 0;
  try {
    doc.write(read('student.html').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,''));
    window.scrollTo = () => {};
    window.CodeMirror = {fromTextArea:() => {
      editorCreations++;
      const input = doc.createElement('textarea'); input.id='qaEditorInput'; doc.querySelector('#editorWrap').append(input);
      return {setOption:(k,v)=>options[k]=v,setSize:()=>{},on:()=>{},refresh:()=>{},focus:()=>{focusCalls++;input.focus();},setCursor:()=>{},getGutterElement:()=>({offsetWidth:32}),getValue:()=>value,setValue:v=>value=v,listSelections:()=>selections,setSelections:v=>selections=v};
    }};
    window.fetch = async (url, init={}) => {
      const route = new URL(url,'http://localhost').pathname;
      calls.push({route,body:init.body});
      let data = {}, status = 200;
      if(route==='/auth/me') data={name:'Alex',role:'student',student_id:'synthetic'};
      else if(route==='/assignments') data={assignments:[]};
      else if(route==='/solved') data={slugs:[]};
      else if(route==='/student/progress') data={problems:[]};
      else if(route==='/decompose_chunks'){status=openingFailure?503:200;data={session_id:'s'+(++session),header:'def employee_update(records):',chunks:steps.map(s=>({...s,prompt:''}))};}
      else if(route.startsWith('/history/')){if(historyGate)await historyGate;if(historyFailure)status=503;data=history;}
      else if(route.startsWith('/session_steps/')){status=stepFailure?503:200;data={chunks:steps};}
      else if(route==='/tutor_chat') data={reply:'What changes from one year to the next?',ready:true,offtrack:true};
      else if(route==='/plan_graph') data=graph;
      else if(route==='/design_review/plan'||route==='/design_review') data={approved,reply:approved?'Your approach is approved.':'Explain how you will preserve the earlier records.',plan_graph:graph};
      else if(route==='/grade_chunk'){
        const index=JSON.parse(init.body).expected_index;
        data=verdict==='correct'?{verdict:'correct',reason:'This step passes.',index:index+1,completed:index===1,solved_independently:true}:verdict==='indeterminate'?{verdict:'indeterminate',reason:'The grader is temporarily unavailable.'}:{verdict:'incorrect',reason:'Try the empty-input case.',failing_cases:['employee_update({})\n\nexpected: {}\nyou gave: None','employee_update({2019: {}})\n\nit raised: KeyError(2018)'],failed_total:5,attempts:1};
      }
      else if(route==='/mark_solved') data={ok:true};
      else if(route==='/graphs'){status=comparisonFailure?503:200;data={plan:graph,code:graph,comparison:{similarity:1,notes:['The structure matches.']}};}
      else if(route.endsWith('/restart')) data={ok:true};
      else throw new Error('Unexpected request: '+route);
      return new window.Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});
    };
    window.eval(['ui.js','cache.js','graphs.js','workspace.js','student.js'].map(read).join('\n')+'\nwindow.inspect = code => eval(code);');
    await tick();
    await window.start(problem);
    const visibleStage = () => [...doc.querySelectorAll('.journey-panel')].filter(el=>!el.hidden).map(el=>el.id);
    assert.deepEqual(visibleStage(),['stageRead']);
    assert(doc.querySelector('#statement pre').textContent.includes('update(records)'));
    assert.equal(doc.querySelector('#readSignature').textContent,'def employee_update(records):');
    assert.equal(doc.querySelector('#chatcol').parentElement.id,'tutorDock');
    assert.equal(doc.querySelector('#tutorDock').hidden,false,'Tutor is available from the question opening');
    assert.equal(doc.querySelector('#cform').inert,false);
    assert.equal(doc.querySelector('#tabCode').getAttribute('aria-disabled'),'true');
    doc.querySelector('#tabCode').click();
    assert.deepEqual(visibleStage(),['stageRead']);
    assert(doc.querySelector('#workspaceNotice').textContent.includes('submit your plan'));
    assert.equal(options.readOnly,'nocursor');
    doc.querySelector('#tabRead').focus();
    doc.querySelector('#tabRead').dispatchEvent(new window.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));
    assert.equal(doc.activeElement.id,'tabCode');
    assert.deepEqual(visibleStage(),['stageRead'],'Reading and planning share one tab');
    assert.equal(doc.querySelector('#problemPaper').parentElement.id,'readQuestion');
    assert.equal(doc.querySelector('#chatcol').parentElement.id,'tutorDock');
    assert.equal(doc.querySelector('#planSubmitBtn').disabled,true);
    assert.equal(doc.querySelector('#planPreview').tagName,'SECTION','The plan graph has no collapse control');
    assert.equal(doc.querySelector('#planEmpty').hidden,false);
    doc.querySelector('#cinput').value='My unsent thinking';
    doc.querySelector('#planUpload').open=true;
    window.pickDesign(new window.File(['diagram'],'plan.pdf',{type:'application/pdf'}));
    doc.querySelector('#planUpload').open=false;
    assert.equal(doc.querySelector('#cinput').value,'My unsent thinking');
    doc.querySelector('#planUpload').open=true;
    assert.equal(doc.querySelector('#designName').textContent,'plan.pdf');
    doc.querySelector('#planUpload').open=false;
    await window.sendToTutor('I will copy the records and update the salaries.');
    await window.inspect('planQueue');
    assert(doc.querySelector('#fork'),'The tutor’s alternative-approach choices remain available');
    assert.equal(doc.querySelector('#planSubmitBtn').disabled,false);
    assert.equal(doc.querySelector('#planEmpty').hidden,true);
    await window.submitPlanGraph();
    assert.equal(doc.querySelector('#tabCode').getAttribute('aria-disabled'),'true');
    assert(doc.querySelector('#designMsg').textContent.includes('preserve'));
    approved=true;
    await window.submitPlanGraph(); await tick();
    assert.deepEqual(visibleStage(),['stageRead'],'Approval must not force a stage change');
    assert.equal(doc.querySelector('#planApproved').hidden,false);
    assert.equal(doc.querySelector('#tabCode').getAttribute('aria-disabled'),'false');
    doc.querySelector('#planContinue').click();
    assert.deepEqual(visibleStage(),['stageCode']);
    assert.equal(doc.querySelector('#stepCount').textContent,'Step 1 of 2');
    assert.equal(doc.querySelector('#tutorDock').hidden,false,'Coding keeps the tutor beside the editor');
    value='    draft = records.copy()'; selections=[{anchor:{line:0,ch:7},head:{line:0,ch:12}}];
    const conversation=doc.querySelector('#clog');
    assert.equal(doc.querySelector('#problemPaper').parentElement.id,'codeQuestion','Coding keeps the question on top');
    assert.equal(doc.querySelector('#problemDetails').open,false,'…minimised, and the student can reopen it');
    const trigger=doc.querySelector('.code-resources [data-resource="plan"]');
    trigger.focus();trigger.click();
    assert.equal(doc.querySelector('#resourceDrawer').hidden,false);
    assert.equal(doc.querySelector('#page').inert,false,'A reference never blocks code or chat');
    assert.equal(doc.querySelector('#stageCode').hidden,false);
    assert.equal(doc.querySelector('#cform').inert,false);
    assert.equal(doc.querySelector('#planCard').parentElement.id,'resourceBody');
    window.openResource('tutor');
    assert.equal(doc.querySelector('#clog'),conversation,'One shared conversation across all stages');
    assert.equal(doc.querySelector('#chatcol').parentElement.id,'tutorDock');
    assert.equal(doc.querySelector('#resourceDrawer').hidden,false,'Asking the tutor leaves the reference open');
    assert.equal(doc.querySelector('#cform').inert,false);
    doc.querySelector('#closeResource').dispatchEvent(new window.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));
    assert.equal(doc.querySelector('#resourceDrawer').hidden,true);
    assert.equal(doc.querySelector('#page').inert,false);
    assert.equal(doc.activeElement,trigger);
    doc.querySelector('#showTutor').click();
    assert.equal(doc.querySelector('#tutorDock').hidden,true);
    assert.equal(doc.querySelector('#cform').inert,true);
    window.openResource('tutor');
    assert.equal(doc.querySelector('#tutorDock').hidden,false);
    assert.equal(doc.querySelector('#clog'),conversation);
    assert.equal(value,'    draft = records.copy()');
    doc.querySelector('#cinput').focus();
    const reply = window.sendToTutor('Why should I copy the record?');
    doc.querySelector('#qaEditorInput').focus();
    assert.equal(doc.activeElement.id,'qaEditorInput');
    await reply;
    assert.equal(doc.activeElement.id,'qaEditorInput','A tutor reply must not steal focus from coding');
    assert.equal(doc.querySelector('#stageCode').hidden,false);
    assert.equal(value,'    draft = records.copy()');
    const layout=doc.querySelector('#studyLayout'), divider=doc.querySelector('#studyDivider');
    Object.defineProperty(layout,'clientWidth',{configurable:true,value:1200});
    doc.querySelector('#tutorDock').getBoundingClientRect=()=>({width:parseInt(layout.style.getPropertyValue('--tutor-width'))||360});
    divider.focus();
    for(const [key,expected] of [['ArrowLeft','380'],['End','480'],['ArrowLeft','480'],['Home','300'],['ArrowRight','300']]){
      divider.dispatchEvent(new window.KeyboardEvent('keydown',{key,bubbles:true}));
      assert.equal(divider.getAttribute('aria-valuenow'),expected);
    }
    assert.equal(value,'    draft = records.copy()','Resizing preserves editor contents');
    window.chooseWorkspaceStage('read'); window.chooseWorkspaceStage('code');
    assert.equal(doc.querySelector('#problemPaper').parentElement.id,'codeQuestion','The question follows the open stage');
    assert.equal(value,'    draft = records.copy()');
    assert.equal(editorCreations,1);
    assert.equal(selections[0].head.ch,12);
    doc.querySelector('#focusWork').click();
    assert(doc.body.classList.contains('focus-workspace'));
    assert.equal(doc.querySelector('#tutorDock').hidden,false,'Focus mode still supports asking questions');
    window.dispatchEvent(new window.KeyboardEvent('keydown',{key:'Escape'}));
    assert(!doc.body.classList.contains('focus-workspace'));
    await doc.querySelector('#submit').onclick();
    assert(doc.querySelector('#msg .failCase'),'Failure details remain available');
    // Several cases now, and the summary states the REAL total - the sandbox
    // caps what it sends back, so counting the listings would under-report.
    assert.equal(doc.querySelectorAll('#msg .failCase pre').length,2,'Every case sent is shown');
    assert(doc.querySelector('#msg .failCase summary').textContent.includes('2 of the 5'),
      doc.querySelector('#msg .failCase summary').textContent);
    assert(doc.querySelector('#msg .failMore').textContent.includes('3 more'),'The hidden ones are counted');
    assert.equal(value,'    draft = records.copy()');
    verdict='indeterminate';await doc.querySelector('#submit').onclick();
    assert.equal(value,'    draft = records.copy()');
    verdict='correct';await doc.querySelector('#submit').onclick();
    assert.equal(doc.querySelector('#reviewBox').hidden,false);
    assert(doc.querySelector('#backToNow').textContent.includes('Continue to step 2'));
    assert(doc.querySelector('#reviewCode').textContent.includes('records.copy()'));
    doc.querySelector('#backToNow').click();
    assert.equal(value,'    ','Continuing must start a new draft, not repeat the submitted answer');
    value='    return updated';comparisonFailure=true;
    await doc.querySelector('#submit').onclick();
    assert.deepEqual(visibleStage(),['stageCode'],'Completion waits for the student to open Reflect');
    assert.equal(doc.querySelector('#finishReview').hidden,false);
    doc.querySelector('#finishReview').click();
    assert.deepEqual(visibleStage(),['stageReflect']);
    assert(doc.querySelector('#reflectSummary').textContent.includes('2 of 2'));
    assert(doc.querySelector('#reflectionCode').textContent.includes('return updated'));
    assert(doc.querySelector('#comparisonStatus button'));
    comparisonFailure=false;doc.querySelector('#comparisonStatus button').click();await tick();
    assert.equal(doc.querySelector('#dualCard').hidden,false);
    assert.equal(doc.querySelector('#comparisonStatus').textContent,'');

    // Upload approval, unavailable step instructions, retry and a safe restart.
    approved=true;await window.start(problem);
    window.chooseWorkspaceStage('read');doc.querySelector('#planUpload').open=true;
    window.pickDesign(new window.File(['diagram'],'plan.pdf',{type:'application/pdf'}));
    stepFailure=true;await window.uploadDesign();await tick();
    assert.equal(doc.querySelector('#planApproved').hidden,false);
    window.chooseWorkspaceStage('code');
    assert.equal(doc.querySelector('#submit').disabled,true);
    assert.equal(options.readOnly,'nocursor');
    assert(doc.querySelector('#msg').textContent.includes('could not be loaded'));
    stepFailure=false;doc.querySelector('#msg button').click();await tick();
    assert.equal(doc.querySelector('#submit').disabled,false);
    window.openRestart();window.closeRestart();
    assert.equal(doc.querySelector('#tabCode').getAttribute('aria-disabled'),'false','Cancel restart keeps approval');
    await window.doRestart();
    assert.deepEqual(visibleStage(),['stageRead']);
    assert.equal(doc.querySelector('#tabCode').getAttribute('aria-disabled'),'true');
    assert.equal(doc.querySelector('#tabReflect').getAttribute('aria-disabled'),'true');
    assert.equal(doc.querySelector('#designPick').hidden,true);
    openingFailure=true;await window.start(problem);
    assert(doc.querySelector('#workspaceStatus button'),'Failed initialization has a visible retry');
    assert.equal(doc.querySelector('#tabCode').getAttribute('aria-disabled'),'true');
    openingFailure=false;doc.querySelector('#workspaceStatus button').click();await tick();
    assert.equal(doc.querySelector('#workspaceStatus').textContent,'');
    history={found:true,design_approved:true,plan:graph,code:graph,comparison:{similarity:1},messages:[{role:'user',content:'Earlier work'}]};
    await window.start(problem);await tick();
    assert.deepEqual(visibleStage(),['stageRead']);
    assert.equal(doc.querySelector('#tabReflect').getAttribute('aria-disabled'),'false');
    assert(doc.querySelector('#reflectSummary').textContent.includes('previous attempt'));
    assert.equal(doc.querySelector('#reflectionCodeDetails').hidden,true,'Historical graphs cannot claim a new completed function');
    assert.equal(doc.querySelectorAll('#clog').length,1);
    // Saved chat and graph share an explicit loading/error boundary.
    let releaseHistory;
    historyGate=new Promise(resolve=>releaseHistory=resolve);
    const restoring=window.start(problem);await tick();
    assert.equal(doc.querySelector('#planPreview').getAttribute('aria-busy'),'true');
    assert.equal(doc.querySelector('#planEmpty').hidden,true);
    assert.equal(doc.querySelector('#planCard').hidden,false);
    assert(doc.querySelector('#planLive .graph-loading'));
    assert.equal(doc.querySelector('#cform button[type="submit"]').disabled,true);
    releaseHistory();historyGate=null;await restoring;
    assert.equal(doc.querySelector('#planPreview').getAttribute('aria-busy'),'false');
    assert(doc.querySelector('#planLive svg'));
    historyFailure=true;await window.start(problem);
    assert(doc.querySelector('#retryHistory'));
    assert.equal(doc.querySelector('#cinput').disabled,true);
    historyFailure=false;doc.querySelector('#retryHistory').click();await tick();
    assert.equal(doc.querySelector('#retryHistory'),null);
    assert.equal(doc.querySelector('#cinput').disabled,false);
    const ids=[...doc.querySelectorAll('[id]')].map(el=>el.id);
    assert.equal(new Set(ids).size,ids.length,'No duplicate IDs');
    assert(calls.some(c=>c.route==='/design_review')&&calls.some(c=>c.route==='/design_review/plan'));
    console.log('PASS: Question+Plan → Code → Reflect; the question rides every stage; persistent tutor; inline references keep code/chat available; both planning methods; approval gates; draft/chat/file preservation; keyboard resizing; replies preserve editor focus; paced steps; grading errors; comparison retry; restart; loading failures; restored work.');
    console.log('DOM behavior only. Browser layout and real CodeMirror still require Chromium.');
  } finally {await window.happyDOM.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
